In [1]:
import zipfile
import os
import cv2

zip_path = "archive.zip"
extract_path = "extracted_images"

# Extract the ZIP file
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

# Read all images
images = []

for root, dirs, files in os.walk(extract_path):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg", ".png", ".bmp")):
            img_path = os.path.join(root, file)
            img = cv2.imread(img_path)

            if img is not None:
                images.append(img)

print("Total images loaded:", len(images))

Total images loaded: 813


In [2]:
images= images[:100]
print("Total images selected:",len(images))

Total images selected: 100


In [3]:
from PIL import Image, ImageEnhance,ImageOps
import pandas as pd

In [4]:
image_info=[]

In [5]:
for i,img in enumerate(images):
  height,width,channel=img.shape
  image_info.append([i+1,height,width,channel])
df=pd.DataFrame(image_info,columns=['image_No','Height','Width','Channel'])
print(df)

    image_No  Height  Width  Channel
0          1     128    128        3
1          2     128    128        3
2          3     128    128        3
3          4     128    128        3
4          5     128    128        3
..       ...     ...    ...      ...
95        96     128    128        3
96        97     128    128        3
97        98     128    128        3
98        99     128    128        3
99       100     128    128        3

[100 rows x 4 columns]


In [6]:
resized_images=[]
for img in images:
  resized_img=cv2.resize(img,(224,224))
  resized_images.append(resized_img)

In [7]:
normalized_images=[]
for img in resized_images:
  normalized_img=img/255.0
  normalized_images.append(normalized_img)
print(len(normalized_images))

100


In [8]:
from cv2 import cvtColor,COLOR_BGR2GRAY
grayscale_images=[]
for img in resized_images:
  grayscale_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  grayscale_images.append(grayscale_img)
print(len(grayscale_images))
grayscale_images


100


[array([[52, 53, 57, ..., 54, 59, 62],
        [52, 53, 57, ..., 47, 52, 56],
        [52, 53, 57, ..., 34, 42, 47],
        ...,
        [61, 55, 45, ..., 32, 28, 26],
        [64, 57, 45, ..., 28, 27, 27],
        [66, 58, 45, ..., 24, 26, 27]], dtype=uint8),
 array([[ 61,  60,  59, ...,  13,  11,  10],
        [ 63,  61,  60, ...,  13,  11,  11],
        [ 65,  63,  60, ...,  13,  12,  12],
        ...,
        [112, 115, 118, ...,  20,  21,  21],
        [101, 102, 104, ...,  20,  21,  21],
        [ 94,  94,  95, ...,  20,  21,  21]], dtype=uint8),
 array([[34, 31, 27, ..., 40, 29, 21],
        [34, 31, 27, ..., 42, 31, 23],
        [35, 32, 29, ..., 46, 34, 27],
        ...,
        [42, 42, 42, ..., 14, 13, 12],
        [45, 45, 45, ..., 13, 13, 13],
        [47, 46, 47, ..., 12, 13, 14]], dtype=uint8),
 array([[ 38,  40,  44, ..., 173, 183, 188],
        [ 41,  42,  45, ..., 173, 180, 185],
        [ 46,  46,  47, ..., 171, 177, 180],
        ...,
        [106,  92,  70, ...,  

In [9]:
from cv2 import cvtColor,COLOR_BGR2GRAY
rgb_images=[]
for img in resized_images:
  rgb_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  rgb_images.append(rgb_img)
print(len(rgb_images))
rgb_images


100


[array([[52, 53, 57, ..., 54, 59, 62],
        [52, 53, 57, ..., 47, 52, 56],
        [52, 53, 57, ..., 34, 42, 47],
        ...,
        [61, 55, 45, ..., 32, 28, 26],
        [64, 57, 45, ..., 28, 27, 27],
        [66, 58, 45, ..., 24, 26, 27]], dtype=uint8),
 array([[ 61,  60,  59, ...,  13,  11,  10],
        [ 63,  61,  60, ...,  13,  11,  11],
        [ 65,  63,  60, ...,  13,  12,  12],
        ...,
        [112, 115, 118, ...,  20,  21,  21],
        [101, 102, 104, ...,  20,  21,  21],
        [ 94,  94,  95, ...,  20,  21,  21]], dtype=uint8),
 array([[34, 31, 27, ..., 40, 29, 21],
        [34, 31, 27, ..., 42, 31, 23],
        [35, 32, 29, ..., 46, 34, 27],
        ...,
        [42, 42, 42, ..., 14, 13, 12],
        [45, 45, 45, ..., 13, 13, 13],
        [47, 46, 47, ..., 12, 13, 14]], dtype=uint8),
 array([[ 38,  40,  44, ..., 173, 183, 188],
        [ 41,  42,  45, ..., 173, 180, 185],
        [ 46,  46,  47, ..., 171, 177, 180],
        ...,
        [106,  92,  70, ...,  

In [10]:

hsv_images=[]
for img in resized_images:
  hsv_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  hsv_images.append(hsv_img)
print(len(hsv_images))

100


In [11]:
normalized_images

[array([[[0.09019608, 0.23921569, 0.17254902],
         [0.09411765, 0.24705882, 0.18039216],
         [0.10196078, 0.2627451 , 0.19215686],
         ...,
         [0.05098039, 0.29411765, 0.10980392],
         [0.05098039, 0.3254902 , 0.11372549],
         [0.05490196, 0.34509804, 0.11372549]],
 
        [[0.09019608, 0.23921569, 0.17254902],
         [0.09411765, 0.24705882, 0.18039216],
         [0.10196078, 0.2627451 , 0.19607843],
         ...,
         [0.05098039, 0.25098039, 0.09803922],
         [0.05490196, 0.28627451, 0.10196078],
         [0.05490196, 0.30980392, 0.10588235]],
 
        [[0.09019608, 0.23921569, 0.17254902],
         [0.09411765, 0.24705882, 0.18039216],
         [0.10588235, 0.2627451 , 0.19607843],
         ...,
         [0.05490196, 0.18039216, 0.0745098 ],
         [0.05490196, 0.22352941, 0.08627451],
         [0.05882353, 0.25490196, 0.09411765]],
 
        ...,
 
        [[0.07058824, 0.30980392, 0.16470588],
         [0.0627451 , 0.28235294, 0.14117

In [12]:
from PIL import Image, ImageEnhance, ImageOps

import os

augmented_dir = "augmented_images"
os.makedirs(augmented_dir, exist_ok=True)

def augment_image(image, image_id):
    image=Image.fromarray(cv2.cvtColor(image,cv2.COLOR_BGR2RGB))
    flipped = ImageOps.mirror(image)
    flipped.save(os.path.join(augmented_dir,f"flipped_{image_id}.png"))

    rotated = image.rotate(30)
    rotated.save(os.path.join(augmented_dir,f"rotated_{image_id}.png"))

    enhancer = ImageEnhance.Brightness(image)
    brighter = enhancer.enhance(1.5)
    brighter.save(os.path.join(augmented_dir, f"brighter_{image_id}.png"))
    w,h=image.size
    zoomed=image.crop((w*0.1,h*0.1,w*0.9,h*0.9))
    zoomed=zoomed.resize((w,h))
    zoomed.save(os.path.join(augmented_dir,f"zoomed_{image_id}.png"))


for i,img in enumerate(resized_images):
  augment_image(img,i)
print("Augmentation completed")

Augmentation completed


In [13]:
import cv2
import numpy as np

def preprocess_image(img):

    # Resize
    img = cv2.resize(img, (224, 224))

    # RGB Conversion
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Normalization
    img = img / 255.0

    return img

# Apply preprocessing to all images
processed_images = []

for img in images:
    processed_images.append(preprocess_image(img))

print("Total processed images:", len(processed_images))

Total processed images: 100
